import type { BuiltinProviderConfig } from '../../store/types'

export const deepseekConfig: BuiltinProviderConfig = {
  id: 'deepseek',
  name: 'DeepSeek',
  type: 'builtin',
  authType: 'userToken',
  apiEndpoint: 'https://chat.deepseek.com/api',
  chatPath: '/v0/chat/completion',
  headers: {
    'Content-Type': 'application/json',
    'Accept': '*/*',
    'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
    'Origin': 'https://chat.deepseek.com',
    'Referer': 'https://chat.deepseek.com/',
    'Sec-Ch-Ua': '"Google Chrome";v="147", "Chromium";v="147", "Not_A Brand";v="24"',
    'Sec-Ch-Ua-Mobile': '?0',
    'Sec-Ch-Ua-Platform': '"Windows"',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36',
    'X-App-Version': '20241129.1',
    'X-Client-Locale': 'zh_CN',
    'X-Client-Platform': 'web',
    'X-Client-Timezone-Offset': '28800',
    'X-Client-Version': '2.0.0',
  },
  enabled: true,
  description: 'DeepSeek web is mode-based. Chat2API uses Expert mode + deep thinking + web search by default.',
  supportedModels: [
    'DeepSeek',
  ],
  modelMappings: {
    'DeepSeek': 'deepseek-chat',
    'DeepSeek-V3.2': 'deepseek-chat',
    'DeepSeek-Search': 'deepseek-chat',
    'DeepSeek-R1': 'deepseek-chat',
    'DeepSeek-R1-Search': 'deepseek-chat',
  },
  credentialFields: [
    {
      name: 'token',
      label: 'User Token',
      type: 'password',
      required: true,
      secret: true,
      order: 10,
      sanitize: 'singleLine',
      enabled: true,
      placeholder: 'Enter DeepSeek user token',
      helpText: 'Copy the token after Authorization: Bearer from DeepSeek web requests, or find the corresponding token in Local Storage. Enter only the token value, without Bearer, quotes, or JSON wrapper.',
    },
  ],
  tokenCheckEndpoint: '/v0/users/current',
  tokenCheckMethod: 'GET',
}

export default deepseekConfig
