import type { BuiltinProviderConfig } from '../../store/types'

export const glmConfig: BuiltinProviderConfig = {
  id: 'glm',
  name: 'GLM',
  type: 'builtin',
  authType: 'token',
  apiEndpoint: 'https://bigmodel.cn/api',
  chatPath: '/biz/trial/response/v4/sse/11989',
  headers: {
    'Content-Type': 'application/json',
    'Accept': 'text/event-stream',
    'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
    'App-Name': 'chatglm',
    'Cache-Control': 'no-cache',
    'Origin': 'https://chatglm.cn',
    'Pragma': 'no-cache',
    'Priority': 'u=1, i',
    'Sec-Ch-Ua': '"Microsoft Edge";v="143", "Chromium";v="143", "Not A(Brand";v="24"',
    'Sec-Ch-Ua-Mobile': '?0',
    'Sec-Ch-Ua-Platform': '"Windows"',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'X-App-Fr': 'browser_extension',
    'X-App-Platform': 'pc',
    'X-App-Version': '0.0.1',
    'X-Device-Brand': '',
    'X-Device-Model': '',
    'X-Lang': 'zh',
  },
  enabled: true,
  description: 'GLM BigModel trial center (domestic), supports GLM-5.1',
  supportedModels: [
    'GLM-5.1',
    'GLM-5',
  ],
  modelMappings: {
    'GLM-5.1': 'glm-5.1',
    'GLM-5': 'glm-5.1',
  },
  credentialFields: [
    {
      name: 'authorization',
      label: 'Authorization',
      type: 'password',
      required: true,
      secret: true,
      order: 10,
      sanitize: 'singleLine',
      placeholder: '粘贴 bigmodel.cn 请求头中的 Authorization 值',
      helpText: '从 bigmodel.cn 成功请求头中复制 Authorization 的值，不要添加 “Authorization:” 前缀。',
    },
    {
      name: 'bigmodelOrganization',
      label: 'Bigmodel Organization',
      type: 'password',
      required: true,
      secret: true,
      order: 20,
      sanitize: 'singleLine',
      placeholder: '粘贴 Bigmodel-Organization 的值',
      helpText: '从 bigmodel.cn 成功请求头中复制 Bigmodel-Organization 的值。',
    },
    {
      name: 'bigmodelProject',
      label: 'Bigmodel Project',
      type: 'password',
      required: true,
      secret: true,
      order: 30,
      sanitize: 'singleLine',
      placeholder: '粘贴 Bigmodel-Project 的值',
      helpText: '从 bigmodel.cn 成功请求头中复制 Bigmodel-Project 的值。',
    },
    {
      name: 'cookies',
      label: 'Cookies (optional)',
      type: 'textarea',
      required: false,
      secret: true,
      order: 40,
      sanitize: 'cookie',
      placeholder: '可选，粘贴 bigmodel.cn 请求头中的 Cookie',
      helpText: 'probe 结果显示当前 GLM 请求不需要 Cookie，默认不发送。仅后续确认需要时填写。',
    },
  ],
  tokenCheckEndpoint: '/biz/trial/response/v4/sse/11989',
  tokenCheckMethod: 'POST',
}

export default glmConfig
